In [2]:
import pandas as pd

# Load data
agua_data = pd.read_excel('../Data/ESTADO_NUTRICIONAL_EN_ADULTOS_DE_18_A_59_ANOS_PERU_2017_2018/1.BD Salud/CAP_800_MUESTRA_DE_AGUA_DE_CONSUMO.xlsx')  # Update the correct file path
nutricion_data = pd.read_excel('../Data/ESTADO_NUTRICIONAL_EN_ADULTOS_DE_18_A_59_ANOS_PERU_2017_2018/1.BD Salud/CAP_400A_SALUD_Y_NUTRICION_ADULTO.xlsx')  # Update the correct file path

In [10]:
agua_data.head(5)

,Conglomerado,Vivienda,HOGAR,ID_ADULTO,DIA,MES,HORA_INICIO,MIN_INICIO,HORA_FINAL,MIN_FINAL,ID_INFORMANTE,801_AGUA_PROCEDENCIA,802_DEPOSITO_TAPADO,803_TRATAMIENTO_AGUA,803_TRATAMIENTO_OTROS,804_CLORO_AGUA,805_COLIFORMES_TOTALES,806_E_COLI,807_INCUBACION_AGUA_24HORAS,807_INCUBACION_AGUA_48HORAS
0,5007,36,11,1,28,3,16,15,16,20,1,1,NaN,1,NaN,5,2,2,1,2
1,5007,41,11,3,28,3,9,20,9,30,3,1,NaN,1,NaN,4,2,2,1,2
2,5013,114,11,2,28,3,8,5,8,8,1,1,NaN,1,NaN,5,2,2,1,2
3,5041,3,11,2,27,11,10,30,10,42,2,1,NaN,1,NaN,1,2,2,1,2
4,5061,80,11,1,26,11,19,20,19,30,2,2,1.0,1,NaN,1,1,1,1,2

In [11]:
nutricion_data.head(5)

,Conglomerado,Vivienda,HOGAR,400_ID,DIA,MES,HORA_INICIO,MIN_INICIO,HORA_FINAL,MIN_FINAL,...,422_SANGRE_VENOSA_AÑO,423_GLUCOSA_ENTERO,423_GLUCOSA_DECIMAL,424_RESULTADO_PESO,424_RESULTADO_TALLA,424_RESULTADO_PERIMETRO_ABDOMINAL,424_RESULTADO_HB,424_RESULTADO_PRESION_ARTERIAL,424_RESULTADO_SANGRE_VENOSA,424_RESULTADO_GLUCOSA
0,5007,36,11,1,29,3,15,55,16,5,...,2018.0,89.0,0.0,1,1,1,1,1.0,1.0,1.0
1,5007,41,11,3,28,3,8,30,8,40,...,2018.0,132.0,0.0,1,1,1,1,1.0,1.0,1.0
2,5013,114,11,2,27,3,14,10,14,17,...,2018.0,97.0,0.0,1,1,1,1,1.0,1.0,1.0
3,5041,3,11,2,23,11,10,10,10,42,...,2017.0,136.0,0.0,1,1,1,1,1.0,1.0,1.0
4,5061,80,11,1,25,11,19,0,19,43,...,2017.0,113.0,0.0,1,1,1,1,1.0,1.0,1.0

In [19]:
# Encontrar los conglomerados comunes entre los dos conjuntos de datos
conglomerados_comunes = set(agua_data['Vivienda']).intersection(set(nutricion_data['Vivienda']))

# Mostrar la cantidad de conglomerados comunes
print(f'Número de conglomerados comunes: {len(conglomerados_comunes)}')

Número de conglomerados comunes: 211

In [12]:
# Merging both datasets on the 'Conglomerado' column
merged_data = pd.merge(agua_data, nutricion_data, on="Conglomerado", how="inner")

In [13]:
nutricion_data.shape

(1089, 94)

In [14]:
agua_data.shape

(911, 20)